package com.quick.tim.mobileserviceprovider.bean;
// Generated 27 Apr, 2013 12:52:34 PM by Hibernate Tools 3.2.1.GA


import com.quick.tim.mobileserviceprovider.entity.Std;
import com.quick.tim.mobileserviceprovider.entity.Sub;
import java.util.Date;


/**
 * Notices generated by hbm2java
 */

public class UpcomingTechnologyBean  implements java.io.Serializable {


     private int technologyid;
     private Std std;
     private Sub sub;
     private Date technologydate;
     private String bywhom;
     private String fordiv;
     private String technologyline;
     private String technologybody;
     private String visibletorole;
     private String category;

    public int getTechnologyid() {
        return technologyid;
    }

    public void setTechnologyid(int technologyid) {
        this.technologyid = technologyid;
    }

    public Std getStd() {
        return std;
    }

    public void setStd(Std std) {
        this.std = std;
    }

    public Sub getSub() {
        return sub;
    }

    public void setSub(Sub sub) {
        this.sub = sub;
    }

    public Date getTechnologydate() {
        return technologydate;
    }

    public void setTechnologydate(Date technologydate) {
        this.technologydate = technologydate;
    }

    public String getBywhom() {
        return bywhom;
    }

    public void setBywhom(String bywhom) {
        this.bywhom = bywhom;
    }

    public String getFordiv() {
        return fordiv;
    }

    public void setFordiv(String fordiv) {
        this.fordiv = fordiv;
    }

    public String getTechnologyline() {
        return technologyline;
    }

    public void setTechnologyline(String technologyline) {
        this.technologyline = technologyline;
    }

    public String getTechnologybody() {
        return technologybody;
    }

    public void setTechnologybody(String technologybody) {
        this.technologybody = technologybody;
    }

    public String getVisibletorole() {
        return visibletorole;
    }

    public void setVisibletorole(String visibletorole) {
        this.visibletorole = visibletorole;
    }

    /**
     * @return the category
     */
    public String getCategory() {
        return category;
    }

    /**
     * @param category the category to set
     */
    public void setCategory(String category) {
        this.category = category;
    }
     
     

}


