package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryDistributionId generated by hbm2java
 */
@Embeddable
public class CategoryDistributionId  implements java.io.Serializable {


     private String category;
     private String technologyName;

    public CategoryDistributionId() {
    }

    public CategoryDistributionId(String category,String technologyName) {
       this.category = category;
       this.technologyName = technologyName;
    }
   
    /**
     * @return the category
     */
    
    @Column(name="category", nullable=false, length=50)
    public String getCategory() {
        return category;
    }

    /**
     * @param category the category to set
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * @return the technologyName
     */
    @Column(name="technology_name", nullable=false, length=50)
    public String getTechnologyName() {
        return technologyName;
    }

    /**
     * @param technologyName the technologyName to set
     */
    
    public void setTechnologyName(String technologyName) {
        this.technologyName = technologyName;
    }
    
}


