package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Oct, 2013 12:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ForumEventDetails generated by hbm2java
 */
@Entity
@Table(name="forum_event_details", schema="public"
)

@SequenceGenerator(name = "id", sequenceName = "public.seq_forum_event_details_id")
public class ForumEventDetails  implements java.io.Serializable {


     private int eventDetailId;
     private Date eventDate;
     private String eventDesc;
     private String eventBody;
     private String eventOwner;
     private byte[] eventImage;
     private Integer parentForumId;

    public ForumEventDetails() {
    }

	
    public ForumEventDetails(int eventDetailId) {
        this.eventDetailId = eventDetailId;
    }
    public ForumEventDetails(int eventDetailId, Date eventDate, String eventDesc, String eventBody, String eventOwner, byte[] eventImage, Integer parentForumId) {
       this.eventDetailId = eventDetailId;
       this.eventDate = eventDate;
       this.eventDesc = eventDesc;
       this.eventBody = eventBody;
       this.eventOwner = eventOwner;
       this.eventImage = eventImage;
       this.parentForumId = parentForumId;
    }
   
    @Id
    @GeneratedValue(generator = "id", strategy = GenerationType.SEQUENCE)
    @Column(name="event_detail_id", unique=true, nullable=false)
    public int getEventDetailId() {
        return this.eventDetailId;
    }
    
    public void setEventDetailId(int eventDetailId) {
        this.eventDetailId = eventDetailId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="event_date", length=35)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }
    
    @Column(name="event_desc", length=100)
    public String getEventDesc() {
        return this.eventDesc;
    }
    
    public void setEventDesc(String eventDesc) {
        this.eventDesc = eventDesc;
    }
    
    @Column(name="event_body", length=1000)
    public String getEventBody() {
        return this.eventBody;
    }
    
    public void setEventBody(String eventBody) {
        this.eventBody = eventBody;
    }
    
    @Column(name="event_owner", length=200)
    public String getEventOwner() {
        return this.eventOwner;
    }
    
    public void setEventOwner(String eventOwner) {
        this.eventOwner = eventOwner;
    }
    
    @Column(name="event_image")
    public byte[] getEventImage() {
        return this.eventImage;
    }
    
    public void setEventImage(byte[] eventImage) {
        this.eventImage = eventImage;
    }
    
    @Column(name="parent_forum_id")
    public Integer getParentForumId() {
        return this.parentForumId;
    }
    
    public void setParentForumId(Integer parentForumId) {
        this.parentForumId = parentForumId;
    }
}


