package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notices generated by hbm2java
 */
@Entity
@Table(name="notices", schema="public"
)
public class Notices  implements java.io.Serializable {


     private int noticeid;
     private Std std;
     private Sub sub;
     private Date noticedate;
     private String bywhom;
     private String fordiv;
     private String noticeline;
     private String noticebody;
     private String visibletorole;

    public Notices() {
    }

	
    public Notices(int noticeid) {
        this.noticeid = noticeid;
    }
    public Notices(int noticeid, Std std, Sub sub, Date noticedate, String bywhom, String fordiv, String noticeline, String noticebody, String visibletorole) {
       this.noticeid = noticeid;
       this.std = std;
       this.sub = sub;
       this.noticedate = noticedate;
       this.bywhom = bywhom;
       this.fordiv = fordiv;
       this.noticeline = noticeline;
       this.noticebody = noticebody;
       this.visibletorole = visibletorole;
    }
   
     @Id 
    
    @Column(name="noticeid", unique=true, nullable=false)
    public int getNoticeid() {
        return this.noticeid;
    }
    
    public void setNoticeid(int noticeid) {
        this.noticeid = noticeid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="forstd")
    public Std getStd() {
        return this.std;
    }
    
    public void setStd(Std std) {
        this.std = std;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subject")
    public Sub getSub() {
        return this.sub;
    }
    
    public void setSub(Sub sub) {
        this.sub = sub;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="noticedate", length=13)
    public Date getNoticedate() {
        return this.noticedate;
    }
    
    public void setNoticedate(Date noticedate) {
        this.noticedate = noticedate;
    }
    
    @Column(name="bywhom", length=200)
    public String getBywhom() {
        return this.bywhom;
    }
    
    public void setBywhom(String bywhom) {
        this.bywhom = bywhom;
    }
    
    @Column(name="fordiv", length=3)
    public String getFordiv() {
        return this.fordiv;
    }
    
    public void setFordiv(String fordiv) {
        this.fordiv = fordiv;
    }
    
    @Column(name="noticeline", length=150)
    public String getNoticeline() {
        return this.noticeline;
    }
    
    public void setNoticeline(String noticeline) {
        this.noticeline = noticeline;
    }
    
    @Column(name="noticebody", length=300)
    public String getNoticebody() {
        return this.noticebody;
    }
    
    public void setNoticebody(String noticebody) {
        this.noticebody = noticebody;
    }
    
    @Column(name="visibletorole", length=32)
    public String getVisibletorole() {
        return this.visibletorole;
    }
    
    public void setVisibletorole(String visibletorole) {
        this.visibletorole = visibletorole;
    }




}


