package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentExamSummary generated by hbm2java
 */
@Entity
@Table(name="student_exam_summary", schema="public"
)
public class StudentExamSummary  implements java.io.Serializable {


     private StudentExamSummaryId id;
     private ExamEntry examEntry;
     private UserMaster userMaster;
     private Date responseDt;
     private Short totalMarks;
     private Short totalObtMarksObj;
     private Short totalObtMarksDesc;
     private String result;

    public StudentExamSummary() {
    }

	
    public StudentExamSummary(StudentExamSummaryId id, ExamEntry examEntry, UserMaster userMaster) {
        this.id = id;
        this.examEntry = examEntry;
        this.userMaster = userMaster;
    }
    public StudentExamSummary(StudentExamSummaryId id, ExamEntry examEntry, UserMaster userMaster, Date responseDt, Short totalMarks, Short totalObtMarksObj, Short totalObtMarksDesc, String result) {
       this.id = id;
       this.examEntry = examEntry;
       this.userMaster = userMaster;
       this.responseDt = responseDt;
       this.totalMarks = totalMarks;
       this.totalObtMarksObj = totalObtMarksObj;
       this.totalObtMarksDesc = totalObtMarksDesc;
       this.result = result;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="exId", column=@Column(name="ex_id", nullable=false) ), 
        @AttributeOverride(name="username", column=@Column(name="username", nullable=false, length=250) ) } )
    public StudentExamSummaryId getId() {
        return this.id;
    }
    
    public void setId(StudentExamSummaryId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ex_id", nullable=false, insertable=false, updatable=false)
    public ExamEntry getExamEntry() {
        return this.examEntry;
    }
    
    public void setExamEntry(ExamEntry examEntry) {
        this.examEntry = examEntry;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false, insertable=false, updatable=false)
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="response_dt", length=13)
    public Date getResponseDt() {
        return this.responseDt;
    }
    
    public void setResponseDt(Date responseDt) {
        this.responseDt = responseDt;
    }
    
    @Column(name="total_marks")
    public Short getTotalMarks() {
        return this.totalMarks;
    }
    
    public void setTotalMarks(Short totalMarks) {
        this.totalMarks = totalMarks;
    }
    
    @Column(name="total_obt_marks_obj")
    public Short getTotalObtMarksObj() {
        return this.totalObtMarksObj;
    }
    
    public void setTotalObtMarksObj(Short totalObtMarksObj) {
        this.totalObtMarksObj = totalObtMarksObj;
    }
    
    @Column(name="total_obt_marks_desc")
    public Short getTotalObtMarksDesc() {
        return this.totalObtMarksDesc;
    }
    
    public void setTotalObtMarksDesc(Short totalObtMarksDesc) {
        this.totalObtMarksDesc = totalObtMarksDesc;
    }
    
    @Column(name="result", length=4)
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }




}


