package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TeacherMaster generated by hbm2java
 */
@Entity
@Table(name="teacher_master", schema="public"
)
public class TeacherMaster  implements java.io.Serializable {


     private String username;
     private UserMaster userMaster;
     private Date dob;
     private Date doj;
     private Character gender;
     private String address;
     private Character isClassTeacher;
     private String ctClass;
     private String isDeleted;

    public TeacherMaster() {
    }

	
    public TeacherMaster(String username, UserMaster userMaster) {
        this.username = username;
        this.userMaster = userMaster;
    }
    public TeacherMaster(String username, UserMaster userMaster, Date dob, Date doj, Character gender, String address, Character isClassTeacher, String ctClass, String isDeleted) {
       this.username = username;
       this.userMaster = userMaster;
       this.dob = dob;
       this.doj = doj;
       this.gender = gender;
       this.address = address;
       this.isClassTeacher = isClassTeacher;
       this.ctClass = ctClass;
       this.isDeleted = isDeleted;
    }
   
     @Id 
    
    @Column(name="username", unique=true, nullable=false, length=250)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", unique=true, nullable=false, insertable=false, updatable=false)
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=13)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="doj", length=13)
    public Date getDoj() {
        return this.doj;
    }
    
    public void setDoj(Date doj) {
        this.doj = doj;
    }
    
    @Column(name="gender", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }
    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="is_class_teacher", length=1)
    public Character getIsClassTeacher() {
        return this.isClassTeacher;
    }
    
    public void setIsClassTeacher(Character isClassTeacher) {
        this.isClassTeacher = isClassTeacher;
    }
    
    @Column(name="ct_class", length=10)
    public String getCtClass() {
        return this.ctClass;
    }
    
    public void setCtClass(String ctClass) {
        this.ctClass = ctClass;
    }
    
    @Column(name="is_deleted", length=1)
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


