package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * upcoming_technology generated by hbm2java
 */
@Entity
@Table(name="upcoming_technology", schema="public"
)
@SequenceGenerator(name = "technologyid", sequenceName = "public.seq_upcoming_technology_technologyid")


public class UpcomingTechnology  implements java.io.Serializable {

     private int technologyid;
     private Std std;
     private Sub sub;
     private Date technologydate;
     private String bywhom;
     private String fordiv;
     private String technologyline;
     private String technologybody;
     private String visibletorole;
     private String category;

    public UpcomingTechnology() {
    }

    public UpcomingTechnology(int technologyid) {
        this.technologyid = technologyid;
    }
    public UpcomingTechnology(int noticeid, Std std, Sub sub, Date technologydate, String bywhom, String fordiv, String technologyline, String technologybody, String visibletorole) {
       this.technologyid = noticeid;
       this.std = std;
       this.sub = sub;
       this.technologydate = technologydate;
       this.bywhom = bywhom;
       this.fordiv = fordiv;
       this.technologyline = technologyline;
       this.technologybody = technologybody;
       this.visibletorole = visibletorole;
    }
   
     @Id 
       @GeneratedValue(generator = "technologyid", strategy = GenerationType.SEQUENCE)
    @Column(name="technologyid", unique=true, nullable=false)
    public int getTechnologyid() {
        return this.technologyid;
    }
    
    public void setTechnologyid(int technologyid) {
        this.technologyid = technologyid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="forstd")
    public Std getStd() {
        return this.std;
    }
    
    public void setStd(Std std) {
        this.std = std;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subject")
    public Sub getSub() {
        return this.sub;
    }
    
    public void setSub(Sub sub) {
        this.sub = sub;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="technologydate", length=13)
    public Date getTechnologydate() {
        return this.technologydate;
    }
    
    public void setTechnologydate(Date technologydate) {
        this.technologydate = technologydate;
    }
    
    @Column(name="bywhom", length=200)
    public String getBywhom() {
        return this.bywhom;
    }
    
    public void setBywhom(String bywhom) {
        this.bywhom = bywhom;
    }
    
    @Column(name="fordiv", length=3)
    public String getFordiv() {
        return this.fordiv;
    }
    
    public void setFordiv(String fordiv) {
        this.fordiv = fordiv;
    }
    
    @Column(name="technologyline", length=150)
    public String getTechnologyline() {
        return this.technologyline;
    }
    
    public void setTechnologyline(String technologyline) {
        this.technologyline = technologyline;
    }
    
    @Column(name="technologybody", length=2000)
    public String getTechnologybody() {
        return this.technologybody;
    }
    
    public void setTechnologybody(String technologybody) {
        this.technologybody = technologybody;
    }
    
    @Column(name="visibletorole", length=32)
    public String getVisibletorole() {
        return this.visibletorole;
    }
    
    public void setVisibletorole(String visibletorole) {
        this.visibletorole = visibletorole;
    }

    /**
     * @return the category
     */
    @Column(name="category", length=32)
    public String getCategory() {
        return category;
    }

    /**
     * @param category the category to set
     */
    public void setCategory(String category) {
        this.category = category;
    }
}


