package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CategoryDistribution generated by hbm2java
 */
@Entity
@Table(name="category_distribution", schema="public"
)
public class CategoryDistribution  implements java.io.Serializable {


     private CategoryDistributionId id;
     private double percentage;

    public CategoryDistribution() {
    }

	
    public CategoryDistribution(CategoryDistributionId id) {
        this.id = id;
    }
    public CategoryDistribution(CategoryDistributionId id, double percentage) {
       this.id = id;
       this.percentage = percentage;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="category", column=@Column(name="category", nullable=false) ), 
        @AttributeOverride(name="technologyName", column=@Column(name="technology_name", nullable=false) ) } )
    
     public CategoryDistributionId getId() {
        return this.id;
    }
    
    public void setId(CategoryDistributionId id) {
        this.id = id;
    }

    /**
     * @return the percentage
     */
    @Column(name="per")
    public double getPercentage() {
        return percentage;
    }

    /**
     * @param percentage the percentage to set
     */
    public void setPercentage(double percentage) {
        this.percentage = percentage;
    }
}


