package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * upcoming_technology generated by hbm2java
 */
@Entity
@Table(name="dict_list", schema="public"
)



public class DictList  implements java.io.Serializable {
    
 /*  meaning character varying(1500),
  labels character varying(300),
  add_date timestamp without time zone,
  owner_username character varying(250),
  owner_name character varying(200), */
    

     private String word;
     private String meaning;
     private String labels;
     private Date addDate;
     private String ownerUsername;
     private String ownerName;
     
     

    public DictList() {
    }

    public DictList(String word) {
        this.word = word;
    }
   
    @Id 
    @Column(name="word", unique=true, nullable=false, length=50)
    public String getWord() {
        return this.word;
    }
    
    public void setWord(String word) {
        this.word = word;
    }
    
    @Column(name="meaning", length=1500)
    public String getMeaning() {
        return meaning;
    }

    public void setMeaning(String meaning) {
        this.meaning = meaning;
    }
    
    @Column(name="labels", length=250)
    public String getLabels() {
        return labels;
    }

    public void setLabels(String labels) {
        this.labels = labels;
    }
    
    @Column(name="add_date")
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    public Date getAddDate() {
        return addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    @Column(name="owner_username", length=250)
    public String getOwnerUsername() {
        return ownerUsername;
    }

    public void setOwnerUsername(String ownerUsername) {
        this.ownerUsername = ownerUsername;
    }

    @Column(name="owner_name", length=200)
    public String getOwnerName() {
        return ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    
}


