package com.quick.tim.mobileserviceprovider.entity;
// Generated Oct 24, 2013 2:28:19 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * ForumEventDetails generated by hbm2java
 */
@Entity
@Table(name="forum_event_details", schema="public"
)
@SequenceGenerator(name = "eventId", sequenceName = "public.seq_forum_event_details_id")
public class ForumEventDetails  implements java.io.Serializable {


     private int eventDetailId;
     private Date eventDate;
     private String eventDesc;
     private String eventBody;
     private String eventOwner;
     private byte[] eventImage;
     private Integer parentForumId;
     private String imageFilename;
     private String videoUrl;
     private Set<ForumEventComments> forumEventCommentses = new HashSet<ForumEventComments>(0);
     private Set<ForumEventLikes> forumEventLikeses = new HashSet<ForumEventLikes>(0);
     
  //   private String stringImage;
     

    public ForumEventDetails() {
    }

	
    public ForumEventDetails(int eventDetailId) {
        this.eventDetailId = eventDetailId;
    }
    public ForumEventDetails(int eventDetailId, Date eventDate, String eventDesc, String eventBody, String eventOwner, byte[] eventImage, Integer parentForumId, String imageFilename, Set<ForumEventComments> forumEventCommentses, Set<ForumEventLikes> forumEventLikeses) {
       this.eventDetailId = eventDetailId;
       this.eventDate = eventDate;
       this.eventDesc = eventDesc;
       this.eventBody = eventBody;
       this.eventOwner = eventOwner;
       this.eventImage = eventImage;
       this.parentForumId = parentForumId;
       this.imageFilename = imageFilename;
       this.forumEventCommentses = forumEventCommentses;
       this.forumEventLikeses = forumEventLikeses;
    }
   
     @Id 
    @GeneratedValue(generator = "eventId", strategy = GenerationType.SEQUENCE)
    @Column(name="event_detail_id", unique=true, nullable=false)
    public int getEventDetailId() {
        return this.eventDetailId;
    }
    
    public void setEventDetailId(int eventDetailId) {
        this.eventDetailId = eventDetailId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="event_date", length=35)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }
    
    @Column(name="event_desc", length=100)
    public String getEventDesc() {
        return this.eventDesc;
    }
    
    public void setEventDesc(String eventDesc) {
        this.eventDesc = eventDesc;
    }
    
    @Column(name="event_body", length=1000)
    public String getEventBody() {
        return this.eventBody;
    }
    
    public void setEventBody(String eventBody) {
        this.eventBody = eventBody;
    }
    
    @Column(name="event_owner", length=200)
    public String getEventOwner() {
        return this.eventOwner;
    }
    
    public void setEventOwner(String eventOwner) {
        this.eventOwner = eventOwner;
    }
    
    @Column(name="event_image")
    public byte[] getEventImage() {
        return this.eventImage;
    }
    
    public void setEventImage(byte[] eventImage) {
        this.eventImage = eventImage;
    }
    
    @Column(name="parent_forum_id")
    public Integer getParentForumId() {
        return this.parentForumId;
    }
    
    public void setParentForumId(Integer parentForumId) {
        this.parentForumId = parentForumId;
    }
    
    @Column(name="image_filename", length=30)
    public String getImageFilename() {
        return this.imageFilename;
    }
    
    public void setImageFilename(String imageFilename) {
        this.imageFilename = imageFilename;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="forumEventDetails")
    public Set<ForumEventComments> getForumEventCommentses() {
        return this.forumEventCommentses;
    }
    
    public void setForumEventCommentses(Set<ForumEventComments> forumEventCommentses) {
        this.forumEventCommentses = forumEventCommentses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="forumEventDetails")
    public Set<ForumEventLikes> getForumEventLikeses() {
        return this.forumEventLikeses;
    }
    
    public void setForumEventLikeses(Set<ForumEventLikes> forumEventLikeses) {
        this.forumEventLikeses = forumEventLikeses;
    }

    /**
     * @return the videoUrl
     */
    @Column(name="video_url")
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * @param videoUrl the videoUrl to set
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }
    /**
     * @return the stringImage
     */
    /* public String getStringImage() {
        return stringImage;
    } */

    /**
     * @param stringImage the stringImage to set
     */
   /* public void setStringImage(String stringImage) {
        this.stringImage = stringImage;
    } */
   
}


