package com.quick.tim.mobileserviceprovider.entity;
// Generated Oct 24, 2013 2:28:19 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.*;

/**
 * ForumEventLikes generated by hbm2java
 */
@Entity
@Table(name="forum_event_likes", schema="public"
)
public class ForumEventLikes  implements java.io.Serializable {


     private ForumEventLikesId id;
     private ForumEventDetails forumEventDetails;
     private String name;
     private Date likeTime;

    public ForumEventLikes() {
    }

	
    public ForumEventLikes(ForumEventLikesId id, ForumEventDetails forumEventDetails) {
        this.id = id;
        this.forumEventDetails = forumEventDetails;
    }
    public ForumEventLikes(ForumEventLikesId id, ForumEventDetails forumEventDetails, String name) {
       this.id = id;
       this.forumEventDetails = forumEventDetails;
       this.name = name;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="eventDetailId", column=@Column(name="event_detail_id", nullable=false) ), 
        @AttributeOverride(name="username", column=@Column(name="username", nullable=false, length=250) ) } )
    public ForumEventLikesId getId() {
        return this.id;
    }
    
    public void setId(ForumEventLikesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_detail_id", nullable=false, insertable=false, updatable=false)
    public ForumEventDetails getForumEventDetails() {
        return this.forumEventDetails;
    }
    
    public void setForumEventDetails(ForumEventDetails forumEventDetails) {
        this.forumEventDetails = forumEventDetails;
    }
    
    @Column(name="name", length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@Column(name="like_time", nullable=false, length=29)
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    public Date getLikeTime() {
        return this.likeTime;
    }
    
    public void setLikeTime(Date likeTime) {
        this.likeTime = likeTime;
    }

}


