package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * QualificationMaster generated by hbm2java
 */
@Entity
@Table(name="qualification_master", schema="public"
)
public class QualificationMaster  implements java.io.Serializable {


     private String qualificationName;
     private Set<UserMaster> userMasters = new HashSet<UserMaster>(0);

    public QualificationMaster() {
    }

	
    public QualificationMaster(String qualificationName) {
        this.qualificationName = qualificationName;
    }
    public QualificationMaster(String qualificationName, Set<UserMaster> userMasters) {
       this.qualificationName = qualificationName;
       this.userMasters = userMasters;
    }
   
     @Id 
    
    @Column(name="qualification_name", unique=true, nullable=false, length=10)
    public String getQualificationName() {
        return this.qualificationName;
    }
    
    public void setQualificationName(String qualificationName) {
        this.qualificationName = qualificationName;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="qualificationMasters")
    public Set<UserMaster> getUserMasters() {
        return this.userMasters;
    }
    
    public void setUserMasters(Set<UserMaster> userMasters) {
        this.userMasters = userMasters;
    }




}


