package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuickNotes generated by hbm2java
 */
@Entity
@Table(name="quick_notes", schema="public"
)
public class QuickNotes  implements java.io.Serializable {


     private QuickNotesId id;
     private UserMaster userMaster;
     private QuickLearn quickLearn;
     private String userNotes;

    public QuickNotes() {
    }

	
    public QuickNotes(QuickNotesId id, UserMaster userMaster, QuickLearn quickLearn) {
        this.id = id;
        this.userMaster = userMaster;
        this.quickLearn = quickLearn;
    }
    public QuickNotes(QuickNotesId id, UserMaster userMaster, QuickLearn quickLearn, String userNotes) {
       this.id = id;
       this.userMaster = userMaster;
       this.quickLearn = quickLearn;
       this.userNotes = userNotes;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="username", column=@Column(name="username", nullable=false, length=250) ), 
        @AttributeOverride(name="uploadId", column=@Column(name="upload_id", nullable=false) ) } )
    public QuickNotesId getId() {
        return this.id;
    }
    
    public void setId(QuickNotesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false, insertable=false, updatable=false)
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="upload_id", nullable=false, insertable=false, updatable=false)
    public QuickLearn getQuickLearn() {
        return this.quickLearn;
    }
    
    public void setQuickLearn(QuickLearn quickLearn) {
        this.quickLearn = quickLearn;
    }
    
    @Column(name="user_notes", length=1000)
    public String getUserNotes() {
        return this.userNotes;
    }
    
    public void setUserNotes(String userNotes) {
        this.userNotes = userNotes;
    }




}


