package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuickNotesId generated by hbm2java
 */
@Embeddable
public class QuickNotesId  implements java.io.Serializable {


     private String username;
     private int uploadId;

    public QuickNotesId() {
    }

    public QuickNotesId(String username, int uploadId) {
       this.username = username;
       this.uploadId = uploadId;
    }
   

    @Column(name="username", nullable=false, length=250)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name="upload_id", nullable=false)
    public int getUploadId() {
        return this.uploadId;
    }
    
    public void setUploadId(int uploadId) {
        this.uploadId = uploadId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuickNotesId) ) return false;
		 QuickNotesId castOther = ( QuickNotesId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && (this.getUploadId()==castOther.getUploadId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + this.getUploadId();
         return result;
   }   


}


