package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StddivId generated by hbm2java
 */
@Embeddable
public class StddivId  implements java.io.Serializable {


     private String std;
     private String div;

    public StddivId() {
    }

    public StddivId(String std, String div) {
       this.std = std;
       this.div = div;
    }
   

    @Column(name="std", nullable=false, length=7)
    public String getStd() {
        return this.std;
    }
    
    public void setStd(String std) {
        this.std = std;
    }

    @Column(name="div", nullable=false, length=3)
    public String getDiv() {
        return this.div;
    }
    
    public void setDiv(String div) {
        this.div = div;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StddivId) ) return false;
		 StddivId castOther = ( StddivId ) other; 
         
		 return ( (this.getStd()==castOther.getStd()) || ( this.getStd()!=null && castOther.getStd()!=null && this.getStd().equals(castOther.getStd()) ) )
 && ( (this.getDiv()==castOther.getDiv()) || ( this.getDiv()!=null && castOther.getDiv()!=null && this.getDiv().equals(castOther.getDiv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStd() == null ? 0 : this.getStd().hashCode() );
         result = 37 * result + ( getDiv() == null ? 0 : this.getDiv().hashCode() );
         return result;
   }   


}


