package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stddiv generated by hbm2java
 */
@Entity
@Table(name="stddiv", schema="public"
)
public class Stddiv  implements java.io.Serializable {


     private StddivId id;
     private Std std;

    public Stddiv() {
    }

    public Stddiv(StddivId id, Std std) {
       this.id = id;
       this.std = std;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="std", column=@Column(name="std", nullable=false, length=7) ), 
        @AttributeOverride(name="div", column=@Column(name="div", nullable=false, length=3) ) } )
    public StddivId getId() {
        return this.id;
    }
    
    public void setId(StddivId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="std", nullable=false, insertable=false, updatable=false)
    public Std getStd() {
        return this.std;
    }
    
    public void setStd(Std std) {
        this.std = std;
    }




}


