package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sub generated by hbm2java
 */
@Entity
@Table(name="sub", schema="public"
)
public class Sub  implements java.io.Serializable {


     private String sub;
     private Set<TeacherStddivSub> teacherStddivSubs = new HashSet<TeacherStddivSub>(0);
     private Set<Notices> noticeses = new HashSet<Notices>(0);
     private Set<Whatsnew> whatsnews = new HashSet<Whatsnew>(0);
     private Set<ExamEntry> examEntries = new HashSet<ExamEntry>(0);
     private Set<QuickLearn> quickLearns = new HashSet<QuickLearn>(0);
     private Set<UserMaster> userMasters = new HashSet<UserMaster>(0);
     private Set<Std> stds = new HashSet<Std>(0);
     private Set<Whoisdoingwhat> whoisdoingwhats = new HashSet<Whoisdoingwhat>(0);

    public Sub() {
    }

	
    public Sub(String sub) {
        this.sub = sub;
    }
    public Sub(String sub, Set<TeacherStddivSub> teacherStddivSubs, Set<Notices> noticeses, Set<Whatsnew> whatsnews, Set<ExamEntry> examEntries, Set<QuickLearn> quickLearns, Set<UserMaster> userMasters, Set<Std> stds, Set<Whoisdoingwhat> whoisdoingwhats) {
       this.sub = sub;
       this.teacherStddivSubs = teacherStddivSubs;
       this.noticeses = noticeses;
       this.whatsnews = whatsnews;
       this.examEntries = examEntries;
       this.quickLearns = quickLearns;
       this.userMasters = userMasters;
       this.stds = stds;
       this.whoisdoingwhats = whoisdoingwhats;
    }
   
     @Id 
    
    @Column(name="sub", unique=true, nullable=false, length=30)
    public String getSub() {
        return this.sub;
    }
    
    public void setSub(String sub) {
        this.sub = sub;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sub")
    public Set<TeacherStddivSub> getTeacherStddivSubs() {
        return this.teacherStddivSubs;
    }
    
    public void setTeacherStddivSubs(Set<TeacherStddivSub> teacherStddivSubs) {
        this.teacherStddivSubs = teacherStddivSubs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sub")
    public Set<Notices> getNoticeses() {
        return this.noticeses;
    }
    
    public void setNoticeses(Set<Notices> noticeses) {
        this.noticeses = noticeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sub")
    public Set<Whatsnew> getWhatsnews() {
        return this.whatsnews;
    }
    
    public void setWhatsnews(Set<Whatsnew> whatsnews) {
        this.whatsnews = whatsnews;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sub")
    public Set<ExamEntry> getExamEntries() {
        return this.examEntries;
    }
    
    public void setExamEntries(Set<ExamEntry> examEntries) {
        this.examEntries = examEntries;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sub")
    public Set<QuickLearn> getQuickLearns() {
        return this.quickLearns;
    }
    
    public void setQuickLearns(Set<QuickLearn> quickLearns) {
        this.quickLearns = quickLearns;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="subs")
    public Set<UserMaster> getUserMasters() {
        return this.userMasters;
    }
    
    public void setUserMasters(Set<UserMaster> userMasters) {
        this.userMasters = userMasters;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="subs")
    public Set<Std> getStds() {
        return this.stds;
    }
    
    public void setStds(Set<Std> stds) {
        this.stds = stds;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sub")
    public Set<Whoisdoingwhat> getWhoisdoingwhats() {
        return this.whoisdoingwhats;
    }
    
    public void setWhoisdoingwhats(Set<Whoisdoingwhat> whoisdoingwhats) {
        this.whoisdoingwhats = whoisdoingwhats;
    }




}


