package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TeacherStddivSubId generated by hbm2java
 */
@Embeddable
public class TeacherStddivSubId  implements java.io.Serializable {


     private String username;
     private String std;
     private String div;
     private String sub;

    public TeacherStddivSubId() {
    }

    public TeacherStddivSubId(String username, String std, String div, String sub) {
       this.username = username;
       this.std = std;
       this.div = div;
       this.sub = sub;
    }
   

    @Column(name="username", nullable=false, length=250)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name="std", nullable=false, length=7)
    public String getStd() {
        return this.std;
    }
    
    public void setStd(String std) {
        this.std = std;
    }

    @Column(name="div", nullable=false, length=3)
    public String getDiv() {
        return this.div;
    }
    
    public void setDiv(String div) {
        this.div = div;
    }

    @Column(name="sub", nullable=false, length=30)
    public String getSub() {
        return this.sub;
    }
    
    public void setSub(String sub) {
        this.sub = sub;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TeacherStddivSubId) ) return false;
		 TeacherStddivSubId castOther = ( TeacherStddivSubId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getStd()==castOther.getStd()) || ( this.getStd()!=null && castOther.getStd()!=null && this.getStd().equals(castOther.getStd()) ) )
 && ( (this.getDiv()==castOther.getDiv()) || ( this.getDiv()!=null && castOther.getDiv()!=null && this.getDiv().equals(castOther.getDiv()) ) )
 && ( (this.getSub()==castOther.getSub()) || ( this.getSub()!=null && castOther.getSub()!=null && this.getSub().equals(castOther.getSub()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getStd() == null ? 0 : this.getStd().hashCode() );
         result = 37 * result + ( getDiv() == null ? 0 : this.getDiv().hashCode() );
         result = 37 * result + ( getSub() == null ? 0 : this.getSub().hashCode() );
         return result;
   }   


}


