package com.quick.tim.mobileserviceprovider.entity;
// Generated 5 Jun, 2013 6:08:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Whoisdoingwhat generated by hbm2java
 */
@Entity
@Table(name="whoisdoingwhat", schema="public"
)
@SequenceGenerator(name = "itemid", sequenceName = "public.seq_whoisdoingwhat_activityid")
public class Whoisdoingwhat  implements java.io.Serializable {


     private int activityid;
     private Std std;
     private Sub sub;
     private Date activitydate;
     private String bywhom;
     private String doingwhat;
     private String fordiv;
     private String topic;
     private String displaynotification;
     private int uploadId;
     private String topicintro;
     private String classToInvoke;
     private String videoUrl;

    public Whoisdoingwhat() {
    }

	
    public Whoisdoingwhat(int activityid) {
        this.activityid = activityid;
    }
    public Whoisdoingwhat(int activityid, Std std, Sub sub, Date activitydate, String bywhom, String doingwhat, String fordiv, String topic, String displaynotification) {
       this.activityid = activityid;
       this.std = std;
       this.sub = sub;
       this.activitydate = activitydate;
       this.bywhom = bywhom;
       this.doingwhat = doingwhat;
       this.fordiv = fordiv;
       this.topic = topic;
       this.displaynotification = displaynotification;
    }
   
    @Id 
    @GeneratedValue(generator = "itemid", strategy = GenerationType.SEQUENCE)
    @Column(name="activityid", unique=true, nullable=false)
    public int getActivityid() {
        return this.activityid;
    }
    
    public void setActivityid(int activityid) {
        this.activityid = activityid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="forstd")
    public Std getStd() {
        return this.std;
    }
    
    public void setStd(Std std) {
        this.std = std;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub")
    public Sub getSub() {
        return this.sub;
    }
    
    public void setSub(Sub sub) {
        this.sub = sub;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="activitydate", length=13)
    public Date getActivitydate() {
        return this.activitydate;
    }
    
    public void setActivitydate(Date activitydate) {
        this.activitydate = activitydate;
    }
    
    @Column(name="bywhom", length=200)
    public String getBywhom() {
        return this.bywhom;
    }
    
    public void setBywhom(String bywhom) {
        this.bywhom = bywhom;
    }
    
    @Column(name="doingwhat", length=150)
    public String getDoingwhat() {
        return this.doingwhat;
    }
    
    public void setDoingwhat(String doingwhat) {
        this.doingwhat = doingwhat;
    }
    
    @Column(name="fordiv", length=3)
    public String getFordiv() {
        return this.fordiv;
    }
    
    public void setFordiv(String fordiv) {
        this.fordiv = fordiv;
    }
    
    @Column(name="topic", length=30)
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }

 @Column(name="displaynotification", length=150)
    public String getDisplaynotification() {
        return this.displaynotification;
    }
    
    public void setDisplaynotification(String displaynotification) {
        this.displaynotification = displaynotification;
    }

    @Column(name="uploadid")
    public int getUploadId() {
        return uploadId;
    }

    public void setUploadId(int uploadId) {
        this.uploadId = uploadId;
    }

    /**
     * @return the topicintro
     */
    @Column(name="topic_intro", length=150)
    public String getTopicintro() {
        return topicintro;
    }

    /**
     * @param topicintro the topicintro to set
     */
    public void setTopicintro(String topicintro) {
        this.topicintro = topicintro;
    }

    /**
     * @return the classToInvoke
     */
    @Column(name="class_to_invoke", length=100)
    public String getClassToInvoke() {
        return classToInvoke;
    }

    /**
     * @param classToInvoke the classToInvoke to set
     */
    public void setClassToInvoke(String classToInvoke) {
        this.classToInvoke = classToInvoke;
    }

    /**
     * @return the videoUrl
     */
    @Column(name="video_url")
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * @param videoUrl the videoUrl to set
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }


}


